local _, addon = ...

local L = {
    ADDON_NAME = "MythicPortalBar",
    DATA_UNAVAILABLE = "Season data is temporarily unavailable",
    LEVEL = "Highest level",
    SCORE = "Dungeon score",
    PORTAL_KNOWN = "Portal learned",
    PORTAL_UNKNOWN = "Portal not learned",
    PORTAL_UNMAPPED = "Portal unavailable",
    CLICK_TO_TELEPORT = "Click to teleport",
    SHIFT_TO_DRAG = "Shift + left-drag to move",
    LOCKED = "Bar is locked",
    OPTIONS = "Options",
    SCALE = "Scale",
    SCALE_TOOLTIP = "Scale the entire dungeon bar.",
    BACKGROUND_ALPHA = "Background opacity",
    BACKGROUND_ALPHA_TOOLTIP = "Adjust the opacity of the bar background.",
    ICON_SIZE = "Icon size",
    ICON_SIZE_TOOLTIP = "Adjust dungeon icon size.",
    SPACING = "Item spacing",
    SPACING_TOOLTIP = "Adjust the space between dungeon items.",
    LOCK_POSITION = "Lock position",
    LOCK_POSITION_TOOLTIP = "Prevent Shift + left-drag from moving the bar.",
    FONT = "Font",
    FONT_TOOLTIP = "Choose a built-in game font.",
    FONT_SIZE = "Font size",
    FONT_SIZE_TOOLTIP = "Adjust the level and score text size.",
    FONT_OUTLINE = "Font outline",
    FONT_OUTLINE_TOOLTIP = "Choose a font outline style.",
    TEXT_COLOR = "Text color",
    TEXT_COLOR_TOOLTIP = "Set the level and score text color.",
    RESET_POSITION = "Reset position",
    RESET_POSITION_TOOLTIP = "Move the bar back above Premade Groups.",
    RESET_ALL = "Restore defaults",
    RESET_ALL_TOOLTIP = "Restore all appearance and position defaults.",
    RESET_POSITION_DONE = "Position reset.",
    RESET_ALL_DONE = "Defaults restored.",
    SCALE_SET = "Scale set to %.2f.",
    SCALE_USAGE = "Usage: /mpb scale <0.5-2.0>",
    COMMANDS = "/mpb options | /mpb reset | /mpb scale <0.5-2.0>",
    FONT_DEFAULT = "Default",
    FONT_CHAT = "Chat",
    FONT_DAMAGE = "Damage",
    OUTLINE_NONE = "None",
    OUTLINE_NORMAL = "Outline",
    OUTLINE_THICK = "Thick outline",
}

if GetLocale() == "zhCN" then
    L.ADDON_NAME = "大秘境传送栏"
    L.DATA_UNAVAILABLE = "赛季数据暂不可用"
    L.LEVEL = "最高完成层数"
    L.SCORE = "地下城评分"
    L.PORTAL_KNOWN = "已解锁传送"
    L.PORTAL_UNKNOWN = "尚未解锁传送"
    L.PORTAL_UNMAPPED = "暂无传送映射"
    L.CLICK_TO_TELEPORT = "点击传送"
    L.SHIFT_TO_DRAG = "Shift + 左键拖动"
    L.LOCKED = "传送栏已锁定"
    L.OPTIONS = "设置"
    L.SCALE = "整体缩放"
    L.SCALE_TOOLTIP = "调整整个地下城栏的缩放。"
    L.BACKGROUND_ALPHA = "背景透明度"
    L.BACKGROUND_ALPHA_TOOLTIP = "调整传送栏背景的不透明度。"
    L.ICON_SIZE = "图标大小"
    L.ICON_SIZE_TOOLTIP = "调整地下城图标尺寸。"
    L.SPACING = "项目间距"
    L.SPACING_TOOLTIP = "调整地下城项目之间的距离。"
    L.LOCK_POSITION = "锁定位置"
    L.LOCK_POSITION_TOOLTIP = "禁止使用 Shift + 左键拖动传送栏。"
    L.FONT = "字体"
    L.FONT_TOOLTIP = "选择游戏内置字体。"
    L.FONT_SIZE = "字号"
    L.FONT_SIZE_TOOLTIP = "调整层数和评分文字大小。"
    L.FONT_OUTLINE = "字体描边"
    L.FONT_OUTLINE_TOOLTIP = "选择文字描边样式。"
    L.TEXT_COLOR = "文字颜色"
    L.TEXT_COLOR_TOOLTIP = "设置层数和评分的文字颜色。"
    L.RESET_POSITION = "重置位置"
    L.RESET_POSITION_TOOLTIP = "将传送栏移回预创建队伍窗口上方。"
    L.RESET_ALL = "恢复默认设置"
    L.RESET_ALL_TOOLTIP = "恢复全部外观和位置默认值。"
    L.RESET_POSITION_DONE = "位置已重置。"
    L.RESET_ALL_DONE = "已恢复默认设置。"
    L.SCALE_SET = "缩放已设置为 %.2f。"
    L.SCALE_USAGE = "用法：/mpb scale <0.5-2.0>"
    L.COMMANDS = "/mpb options | /mpb reset | /mpb scale <0.5-2.0>"
    L.FONT_DEFAULT = "默认"
    L.FONT_CHAT = "聊天"
    L.FONT_DAMAGE = "伤害数字"
    L.OUTLINE_NONE = "无"
    L.OUTLINE_NORMAL = "细描边"
    L.OUTLINE_THICK = "粗描边"
end

addon.L = L
